<?php
/**
 * @var \Hz\PriceMonitor\Block\Product $block
 */
?>
<table style="margin-top:150px;">
	<thead>
		<th><?php echo __('Name') ?></th>
		<th><?php echo __('Price') ?></th>
		<th><?php echo __('Url') ?></th>
		<th><?php echo __('Detail') ?></th>
	</thead>
	<tbody>
		<?php foreach ($block->getListProduct() as $item) : ?>
			<tr>
				<td><?php echo $item->getName() ?></td>
				<td><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($item->getPrice(),true,false)  ?></td>
				<td><?php echo $item->getUrl() ?></td>
				<td><a href="<?php echo $this->getUrl('*/product/detail', ['id' => $item->getId()]) ?>"><?php echo __('Detail') ?></a></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<a href="<?php echo $this->getUrl('*/product/') ?>"><?php echo __('Go To Add Page') ?></a>